//
//  dummydata.swift
//  EMovies
//
//  Created by Allan on 5/13/24.
//

import Foundation

let dummyTrending = [Result(backdropPath: "/backdrop1.jpg", id: 1, originalName: "", originalTitle: "Original Title 1", overview: "Overview 1", posterPath: "/poster1.jpg", mediaType: .movie, adult: false, name: "", originalLanguage: .en, genreId: [1, 2, 3], popularity: 7.5, releaseDate: "2024-05-01", firstAirDate: nil, video: nil, voteAverage: 8.0, voteCount: 100, originCountry: nil),Result(backdropPath: "/backdrop2.jpg", id: 2, originalName: "", originalTitle: "Original Title 2", overview: "Overview 2", posterPath: "/poster2.jpg", mediaType: .tv, adult: false, name: "Title 2", originalLanguage: .en, genreId: [4, 5, 6], popularity: 8.5, releaseDate: nil, firstAirDate: "2024-05-02", video: nil, voteAverage: 9.0, voteCount: 200, originCountry: ["US"]), Result(backdropPath: "/backdrop2.jpg", id: 3, originalName: "", originalTitle: "Original Title 2", overview: "Overview 2", posterPath: "/poster2.jpg", mediaType: .tv, adult: false, name: "Title 2", originalLanguage: .en, genreId: [4, 5, 6], popularity: 8.5, releaseDate: nil, firstAirDate: "2024-05-02", video: nil, voteAverage: 9.0, voteCount: 200, originCountry: ["US"]), Result(backdropPath: "/backdrop2.jpg", id: 4, originalName: "", originalTitle: "Original Title 2", overview: "Overview 2", posterPath: "/poster2.jpg", mediaType: .tv, adult: false, name: "Title 2", originalLanguage: .en, genreId: [4, 5, 6], popularity: 8.5, releaseDate: nil, firstAirDate: "2024-05-02", video: nil, voteAverage: 9.0, voteCount: 200, originCountry: ["US"]), Result(backdropPath: "/backdrop2.jpg", id: 5, originalName: "", originalTitle: "Original Title 2", overview: "Overview 2", posterPath: "/poster2.jpg", mediaType: .tv, adult: false, name: "Title 2", originalLanguage: .en, genreId: [4, 5, 6], popularity: 8.5, releaseDate: nil, firstAirDate: "2024-05-02", video: nil, voteAverage: 9.0, voteCount: 200, originCountry: ["US"]), Result(backdropPath: "/backdrop2.jpg", id: 6, originalName: "", originalTitle: "Original Title 2", overview: "Overview 2", posterPath: "/poster2.jpg", mediaType: .tv, adult: false, name: "Title 2", originalLanguage: .en, genreId: [4, 5, 6], popularity: 8.5, releaseDate: nil, firstAirDate: "2024-05-02", video: nil, voteAverage: 9.0, voteCount: 200, originCountry: ["US"]), Result(backdropPath: "/backdrop2.jpg", id: 7, originalName: "", originalTitle: "Original Title 2", overview: "Overview 2", posterPath: "/poster2.jpg", mediaType: .tv, adult: false, name: "Title 2", originalLanguage: .en, genreId: [4, 5, 6], popularity: 8.5, releaseDate: nil, firstAirDate: "2024-05-02", video: nil, voteAverage: 9.0, voteCount: 200, originCountry: ["US"])]
